import { ensureProjects, launch, SHOTS, BASE, findings, note, api } from './lib.js'
const fx = await ensureProjects()
const { browser, page } = await launch('plugins')
await page.goto(BASE)
await page.waitForLoadState('networkidle')
console.log('tabs before:', await page.locator('[role="tab"]').allTextContents())
await page.locator('button[title*="ettings" i], button[aria-label*="ettings" i]').first().click()
await page.waitForTimeout(600)
await page.getByText('Plugins', { exact: true }).last().click()
await page.waitForTimeout(500)
await page.screenshot({ path: `${SHOTS}/82a-after-plugins-click.png` })
const chatToggle = page.getByRole('switch').first()
console.log('chat toggle checked before:', await chatToggle.getAttribute('aria-checked'))
await chatToggle.click()
await page.waitForTimeout(1200)
const list = (await api('/api/plugins/list')).body as { plugins: { id: string; enabled: boolean }[] }
console.log('api after toggle:', list.plugins.map((p) => `${p.id}=${p.enabled}`).join(' '))
const agents = (await api('/api/agents')).body as { defaults: { id: string }[] }
console.log('chat agents still listed:', agents.defaults.filter((a) => a.id.startsWith('chat-')).length)
await page.screenshot({ path: `${SHOTS}/82-plugin-off.png` })
// close settings and look at home
await page.keyboard.press('Escape')
await page.goto(BASE)
await page.waitForLoadState('networkidle')
await page.waitForTimeout(500)
const tabs = await page.locator('[role="tab"]').allTextContents()
console.log('tabs with chat off:', tabs)
if (tabs.includes('Chat')) note('Chat tab still shown with the plugin disabled')
if (!tabs.includes('Unavailable')) note('no "Unavailable" tab although a chat project exists while the plugin is off')
await page
  .getByRole('tab', { name: 'Unavailable' })
  .click()
  .catch(() => {})
await page.screenshot({ path: `${SHOTS}/83-unavailable-tab.png` })
console.log('unavailable tab text:', (await page.locator('body').innerText()).replace(/\n+/g, ' | ').slice(0, 300))
// open the chat project while disabled
await page.goto(`${BASE}/p/${fx.chat}`)
await page.waitForLoadState('networkidle')
await page.waitForTimeout(500)
await page.screenshot({ path: `${SHOTS}/84-chat-project-disabled.png` })
console.log('chat project page:', (await page.locator('body').innerText()).replace(/\n+/g, ' | ').slice(0, 300))
// re-enable
await api('/api/plugins/openfox-chat/enable', { method: 'POST', json: {} })
console.log('findings:', findings.join('\n') || 'none')
await browser.close()
